INSERT INTO `franchisee_management_system`.`franchisee_details` (`Franchisee_ID`, `Landmark_I`, `Landmark_II`, `Area`, `City`, `State`, `Pin_Number`, `ContactNumber`, `OpeningTime`, `ClosingTime`) VALUES ('FR_001', 'City Gold', 'Ashram Road', 'Navrangpur', 'Ahmedabad', 'Gujarat', '380015', '9898475755', '11:00 AM', '11:00 PM');
INSERT INTO `franchisee_management_system`.`franchisee_details` (`Franchisee_ID`, `Landmark_I`, `Landmark_II`, `Area`, `City`, `State`, `Pin_Number`, `ContactNumber`, `OpeningTime`, `ClosingTime`) VALUES ('FR_002', 'Bus Stand', '', 'Paldi', 'Ahmedabad', 'Gujarat', '380019', '9898575755', '10:00 AM', '12:00 PM');
INSERT INTO `franchisee_management_system`.`franchisee_details` (`Franchisee_ID`, `Landmark_I`, `Area`, `City`, `State`, `Pin_Number`, `ContactNumber`, `OpeningTime`, `ClosingTime`) VALUES ('FR_003', 'Himalaya Mall', 'Drive In', 'Ahmedabad', 'Gujarat', '380016', '9898875755', '10:00 AM', '10:00 PM');

Insert into `franchisee_management_system`.`franchisee_details` (Franchisee_ID,Landmark_I,Landmark_II,Area,City,State,Pin_Number,ContactNumber,OpeningTime,ClosingTime)values('FR_004','Platinum Gold','Nr Big Baazar','Kalawad Road','Rajkot','Gujarat','360001','0201501011','8am','8pm');
Insert into `franchisee_management_system`.`franchisee_details` (Franchisee_ID,Landmark_I,Landmark_II,Area,City,State,Pin_Number,ContactNumber,OpeningTime,ClosingTime)values('FR_005','Silver Diamond','Nr Imperial Palace','Yagnik Road','Rajkot','Gujarat','360001','0201501028','8:00am','8:00pm'); 
Insert into `franchisee_management_system`.`franchisee_details` (Franchisee_ID,Landmark_I,Landmark_II,Area,City,State,Pin_Number,ContactNumber,OpeningTime,ClosingTime)values('FR_006','Platinum Blue','Nr Pantaloons','150ft Road','Rajkot','Gujarat','360001','0201501039','8:00am','8:00pm');
Insert into `franchisee_management_system`.`franchisee_details` (Franchisee_ID,Landmark_I,Landmark_II,Area,City,State,Pin_Number,ContactNumber,OpeningTime,ClosingTime)values('FR_007','Silver Oak','Nr Jade Blue','Jamnagar Road','Rajkot','Gujarat','360001','0201501049','8:00am','8:00pm');
Insert into `franchisee_management_system`.`franchisee_details`(Franchisee_ID,Landmark_I,Landmark_II,Area,City,State,Pin_Number,ContactNumber,OpeningTime,ClosingTime)values('FR_008','Platinum Nest','Nr Big Baazar','Kalawad Road','Rajkot','Gujarat','360001','0201501054','8:00am','8:00pm');
Insert into `franchisee_management_system`.`franchisee_details` (Franchisee_ID,Landmark_I,Landmark_II,Area,City,State,Pin_Number,ContactNumber,OpeningTime,ClosingTime)values('FR_009','Golden Bird','Nr Alpha One','Gondal Road','Rajkot','Gujarat','360001','0201501068','8:00am','8:00pm');
Insert into `franchisee_management_system`.`franchisee_details` (Franchisee_ID,Landmark_I,Landmark_II,Area,City,State,Pin_Number,ContactNumber,OpeningTime,ClosingTime)values('FR_010','Silver Sparrow','Nr Big Baazar','Ahmedabad Road','Rajkot','Gujarat','360001','0201501085','8:00am','8:00pm');
Insert into `franchisee_management_system`.`franchisee_details` (Franchisee_ID,Landmark_I,Landmark_II,Area,City,State,Pin_Number,ContactNumber,OpeningTime,ClosingTime)values('FR_011','Brown petal','Nr SNK ','Palace Road','Rajkot','Gujarat','360001','0201501118','8:00am','8:00pm');
Insert into `franchisee_management_system`.`franchisee_details` (Franchisee_ID,Landmark_I,Landmark_II,Area,City,State,Pin_Number,ContactNumber,OpeningTime,ClosingTime)values('FR_012','Blue Moon','Nr Blue Club','Manahar Plot','Rajkot','Gujarat','360001','0201501119','8:00am','8:00pm');
Insert into `franchisee_management_system`.`franchisee_details` (Franchisee_ID,Landmark_I,Landmark_II,Area,City,State,Pin_Number,ContactNumber,OpeningTime,ClosingTime)values('FR_013','Red Sun','Nr Santushti','Sg Road','Ahmedabad','Gujarat','380015','0201501121','8:00am','8:00pm');